name: realinn
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.4.0-282.3.beta <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.3.1
  flutter_iconly: ^1.0.2
  auto_size_text: ^3.0.0
  animations: ^2.0.2
  easy_localization: ^3.0.2
  lottie: ^3.1.3
  flutter_riverpod: ^2.6.1
  loading_animation_widget: ^1.1.0+1
  adaptive_theme: ^3.1.1
  fluttertoast: ^8.2.2
  shimmer: ^3.0.0
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  path_provider: ^2.0.9
  flutter_secure_storage: ^8.0.0
  validators: ^3.0.0
  intl: ^0.19.0
  firebase_core: ^3.4.0
  firebase_messaging: ^15.1.0
  url_launcher: ^6.0.20
  flutter_displaymode: ^0.6.0
  internet_connection_checker: ^3.0.1
  app_settings: ^6.1.1
  font_awesome_flutter: ^10.1.0
  flutter_web_browser: "^0.17.1"
  uuid: ^4.5.1
  path: ^1.8.1
  loader_overlay: ^4.0.4+1
  collection: ^1.16.0
  connectivity_plus: ^6.1.4
  timeago: ^3.3.0
  html_unescape: ^2.0.0
  form_field_validator: ^1.1.0
  uni_links: ^0.5.1
  webview_flutter: ^4.0.5
  regexed_validator: ^2.0.0+1
  google_sign_in: ^6.0.2
  dio: ^5.0.3
  dio_cache_interceptor: ^4.0.3
  google_mobile_ads: ^5.2.0
  cookie_consent: ^1.0.0
  get: ^4.6.5
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  flutter_typeahead: ^5.2.0
  optimize_battery: ^0.0.4
  location: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/maskable-icon.png"
  adaptive_icon_background: "assets/maskable-icon.png"
  adaptive_icon_foreground: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
    - assets/jsons/
    - assets/lang/
    - assets/png/
    - assets/svg/
    - assets/svg/nav/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 500
    - family: Nexa
      fonts:
        - asset: assets/fonts/Nexa-Heavy.ttf
          weight: 700
        - asset: assets/fonts/Nexa-ExtraLight.ttf
          weight: 300
    - family: Borela
      fonts:
        - asset: assets/fonts/BORELA.ttf
          weight: 700
dependency_overrides:
  modal_bottom_sheet: ^3.0.0-pre
  http: ^1.1.0
  visibility_detector: ^0.4.0+2



